version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: PWD
          command: pwd
      - run:
          name: list place
          command: ls
      - run:
          name: Got to package
          command: cd packages/test
      - run:
          name: Verify if I be inside of correct folder
          command: pwd
      - run:
          name: Create package
          command: dpkg --build deb
