version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install aws dependencies
          command: sudo apt-get install git
      - run:
          name: Geting version patch
          command: echo Version patch ${CIRCLE_TAG}
      - run:
          name: Create package
          command: dpkg --build patch_${CIRCLE_TAG}/deb

workflows:
  version: 2
  build_package:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

