version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node
    tag: /release-.*/

    steps:
      - checkout
      - run:
          name: Geting version patch
          command: echo Version patch ${CIRCLE_TAG}
      - run:
          name: Create package
          command: dpkg --build patch_${CIRCLE_TAG}/deb

          
