version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node
    tags:
      only:
        - tests
    steps:
     - checkout
     - run:
         name: Detect the new package
         command: |
           echo "export parche=$(ls -dt */ |head -n1)" >> $BASH_ENV
     - run:
         name: Create new package
         command: |
           echo "Parche select: ${parche}"
           dpkg --build ${parche}deb
     - run:
         name: Check Package information 
         command: dpkg --info ${parche}deb.deb
     - run:
         name: Post package as release or testing 
         command: |
           echo "Its a releas? patch ${CIRCLE_TAG}"
           if [ "${CIRCLE_TAG}" == "" ]; then
              echo "NO"
              cat ${parche}deb.deb|gzip|curl -X PUT --upload-file "-" https://transfer.sh/parche.gz
           else
              echo "Si. Version: ${CIRCLE_TAG} release"
           fi
