version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: PWD
          command: pwd
      - run:
          name: list place
          command: ls
      - run:
          name: Create package
          command: dpkg --build test/deb
