version: 2
jobs:
  build:
    working_directory: /home/circleci/
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
        name: Greeting
        command: echo Hello, world.
      - run:
        name: Go correct folder
        command: cd test
      - run:
        name: Create package
        command: dpkg --build deb
